// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: replitlmpb/replitlm.proto

package replitlmpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CodeGeneratorClient is the client API for CodeGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeGeneratorClient interface {
	// Send prompt to ReplitLM
	SendPrompt(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeResponse, error)
}

type codeGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeGeneratorClient(cc grpc.ClientConnInterface) CodeGeneratorClient {
	return &codeGeneratorClient{cc}
}

func (c *codeGeneratorClient) SendPrompt(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeResponse, error) {
	out := new(CodeResponse)
	err := c.cc.Invoke(ctx, "/replitlm.CodeGenerator/SendPrompt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeGeneratorServer is the server API for CodeGenerator service.
// All implementations must embed UnimplementedCodeGeneratorServer
// for forward compatibility
type CodeGeneratorServer interface {
	// Send prompt to ReplitLM
	SendPrompt(context.Context, *CodeRequest) (*CodeResponse, error)
	mustEmbedUnimplementedCodeGeneratorServer()
}

// UnimplementedCodeGeneratorServer must be embedded to have forward compatible implementations.
type UnimplementedCodeGeneratorServer struct {
}

func (UnimplementedCodeGeneratorServer) SendPrompt(context.Context, *CodeRequest) (*CodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrompt not implemented")
}
func (UnimplementedCodeGeneratorServer) mustEmbedUnimplementedCodeGeneratorServer() {}

// UnsafeCodeGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeGeneratorServer will
// result in compilation errors.
type UnsafeCodeGeneratorServer interface {
	mustEmbedUnimplementedCodeGeneratorServer()
}

func RegisterCodeGeneratorServer(s grpc.ServiceRegistrar, srv CodeGeneratorServer) {
	s.RegisterService(&CodeGenerator_ServiceDesc, srv)
}

func _CodeGenerator_SendPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeGeneratorServer).SendPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replitlm.CodeGenerator/SendPrompt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeGeneratorServer).SendPrompt(ctx, req.(*CodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeGenerator_ServiceDesc is the grpc.ServiceDesc for CodeGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replitlm.CodeGenerator",
	HandlerType: (*CodeGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPrompt",
			Handler:    _CodeGenerator_SendPrompt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "replitlmpb/replitlm.proto",
}
